import { StyleSheet } from 'react-native';
import { colors, fontSize, radius, shadow, spacing } from '@/theme';
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    backgroundColor: colors.background,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  appName: {
    color: colors.primaryDark,
    fontSize: fontSize.xxl,
    fontWeight: '900',
  },
  headerHint: {
    color: colors.textSoft,
    fontSize: fontSize.sm,
    fontWeight: '700',
    marginTop: 2,
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  iconButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: colors.card,
    ...shadow.soft,
  },
  searchBox: {
    height: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radius.pill,
    marginTop: spacing.md,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.soft,
  },
  searchIconBubble: {
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
  },
  searchText: {
    flex: 1,
    color: colors.textSoft,
    fontSize: fontSize.md,
    fontWeight: '600',
  },
  tabsShell: {
    backgroundColor: colors.background,
    paddingBottom: spacing.sm,
  },
  tabsContent: {
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  subTabsShell: {
    backgroundColor: colors.background,
    paddingBottom: spacing.sm,
  },
  subTabsContent: {
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
  },
  subTabButton: {
    minHeight: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: colors.primarySubtle,
  },
  subTabButtonActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  subTabText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
  },
  subTabTextActive: {
    color: colors.primaryDark,
  },
  tabButton: {
    minWidth: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: colors.primarySubtle,
  },
  activeTabButton: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    ...shadow.card,
  },
  tabText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    fontWeight: '800',
  },
  activeTabText: {
    color: colors.white,
  },
  tabIndicator: {
    position: 'absolute',
    right: spacing.sm,
    bottom: 4,
    left: spacing.sm,
    height: 3,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.86)',
  },
  listContent: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxl,
  },
  continueSection: {
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  sectionAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  sectionActionText: {
    color: colors.primaryDark,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  continueList: {
    gap: spacing.md,
    paddingRight: spacing.md,
  },
  continueCard: {
    width: 156,
    borderRadius: radius.lg,
    padding: spacing.sm,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.primarySubtle,
    ...shadow.soft,
  },
  continueCover: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: radius.md,
    backgroundColor: colors.primarySubtle,
  },
  continueProgressTrack: {
    overflow: 'hidden',
    height: 4,
    borderRadius: radius.pill,
    marginTop: spacing.sm,
    backgroundColor: colors.primarySubtle,
  },
  continueProgressFill: {
    height: 4,
    backgroundColor: colors.primary,
  },
  continueTitle: {
    color: colors.text,
    fontSize: fontSize.sm,
    fontWeight: '900',
    lineHeight: 18,
    marginTop: spacing.sm,
  },
  pressed: {
    opacity: 0.76,
  },
  videoRow: {
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  emptyListContent: {
    flexGrow: 1,
  },
  loadingWrap: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
  },
  loadingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.xs,
  },
  loadingMoreFooter: {
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: spacing.lg,
  },
  stateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxl,
  },
  emptyIconWrap: {
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
  },
  stateTitle: {
    color: colors.text,
    fontSize: fontSize.xl,
    fontWeight: '900',
    marginTop: spacing.md,
  },
  stateText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 20,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
});
