import { StyleSheet } from 'react-native';
import { colors, fontSize, radius, shadow, spacing } from '@/theme';
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topBar: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.primary,
  },
  backButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  topTitle: {
    flex: 1,
    color: colors.white,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  scrollContent: {
    paddingBottom: 30,
  },
  scrollContentLandscape: {
    flexGrow: 1,
  },
  playerShell: {
    width: '100%',
    aspectRatio: 16 / 9,
    overflow: 'hidden',
    backgroundColor: '#000000',
  },
  playerShellLandscape: {
    flex: 1,
    aspectRatio: undefined,
  },
  video: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
  },
  playerLoading: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
  },
  playerErrorOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxl,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  completedOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xxl,
    backgroundColor: 'rgba(0, 0, 0, 0.46)',
  },
  playerOverlayTitle: {
    color: colors.white,
    fontSize: fontSize.xl,
    fontWeight: '900',
    marginTop: spacing.sm,
  },
  playerOverlayText: {
    color: colors.primarySoft,
    fontSize: fontSize.md,
    lineHeight: 20,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
  replayButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radius.pill,
    marginTop: spacing.md,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.white,
  },
  replayText: {
    color: colors.primaryDark,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  gestureHint: {
    position: 'absolute',
    alignSelf: 'center',
    top: '42%',
    borderRadius: radius.pill,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
  },
  gestureHintText: {
    color: colors.white,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  controlBar: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    left: 0,
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
  },
  controlButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  progressTrack: {
    flex: 1,
    height: 28,
    justifyContent: 'center',
  },
  progressRail: {
    overflow: 'hidden',
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(255, 255, 255, 0.28)',
  },
  progressFill: {
    height: 4,
    backgroundColor: colors.primary,
  },
  timeText: {
    minWidth: 42,
    color: colors.white,
    fontSize: fontSize.sm,
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  speedBar: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    flexDirection: 'row',
    gap: spacing.xs,
    borderRadius: radius.pill,
    padding: spacing.xs,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
  },
  speedButton: {
    minWidth: 40,
    alignItems: 'center',
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
  },
  speedButtonActive: {
    backgroundColor: colors.white,
  },
  speedText: {
    color: colors.white,
    fontSize: fontSize.xs,
    fontWeight: '900',
  },
  speedTextActive: {
    color: colors.primaryDark,
  },
  unsupportedPlayer: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xxl,
    backgroundColor: '#000000',
  },
  unsupportedTitle: {
    color: colors.white,
    fontSize: fontSize.lg,
    fontWeight: '900',
    marginTop: spacing.md,
    textAlign: 'center',
  },
  unsupportedActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: radius.pill,
    backgroundColor: colors.primary,
    ...shadow.card,
  },
  unsupportedActionText: {
    color: colors.white,
    fontSize: fontSize.md,
    fontWeight: '900',
  },
  unsupportedHintMuted: {
    marginTop: spacing.lg,
    color: '#a98497',
    fontSize: fontSize.sm,
    textAlign: 'center',
  },
  unsupportedText: {
    maxWidth: 310,
    color: '#d8a9bc',
    fontSize: fontSize.md,
    lineHeight: 21,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
  body: {
    gap: spacing.lg,
    padding: spacing.lg,
  },
  detailCard: {
    borderRadius: radius.lg,
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.card,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  title: {
    flex: 1,
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 30,
  },
  badge: {
    overflow: 'hidden',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    color: colors.white,
    fontSize: fontSize.sm,
    fontWeight: '900',
    backgroundColor: colors.primary,
  },
  badgeMuted: {
    backgroundColor: colors.textMuted,
  },
  authorBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  avatar: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
  },
  avatarText: {
    color: colors.primaryDark,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  authorContent: {
    flex: 1,
  },
  authorName: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  providerText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    marginTop: 3,
  },
  episodePanel: {
    marginTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.primarySubtle,
    paddingTop: spacing.lg,
  },
  episodePanelHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  currentEpisodeText: {
    flex: 1,
    color: colors.primaryDark,
    fontSize: fontSize.sm,
    fontWeight: '900',
    textAlign: 'right',
  },
  selectorLabel: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '900',
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
  },
  lineTabs: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingVertical: spacing.xs,
  },
  lineTab: {
    minHeight: 36,
    justifyContent: 'center',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.primarySoft,
  },
  lineTabActive: {
    backgroundColor: colors.primary,
  },
  lineTabText: {
    color: colors.primaryDark,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  lineTabTextActive: {
    color: colors.white,
  },
  episodeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  episodeCell: {
    width: 74,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.sm,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    backgroundColor: colors.primarySoft,
  },
  episodeCellLazy: {
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: colors.primarySoft,
  },
  episodeCellActive: {
    backgroundColor: colors.primary,
    borderWidth: 0,
  },
  episodeCellText: {
    color: colors.primaryDark,
    fontSize: fontSize.sm,
    fontWeight: '900',
    textAlign: 'center',
  },
  episodeCellTextActive: {
    color: colors.white,
  },
  episodeCellHint: {
    color: colors.textSoft,
    fontSize: 10,
    fontWeight: '800',
    marginTop: 2,
    textAlign: 'center',
  },
  episodeCellHintActive: {
    color: colors.white,
  },
  noEpisodesText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
    marginTop: spacing.lg,
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  metaPill: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    backgroundColor: colors.primarySoft,
  },
  metaText: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  tagsSection: {
    marginTop: spacing.lg,
  },
  sectionLabel: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    marginBottom: spacing.sm,
  },
  tagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  tagPill: {
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colors.cardMuted,
    borderWidth: 1,
    borderColor: colors.primarySubtle,
  },
  tagText: {
    color: colors.primaryDark,
    fontSize: fontSize.sm,
    fontWeight: '800',
  },
  actionRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.lg,
  },
  actionButton: {
    flex: 1,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    borderRadius: radius.pill,
    backgroundColor: colors.primarySoft,
  },
  actionButtonActive: {
    backgroundColor: colors.primary,
  },
  favoriteActionWrap: {
    flex: 1,
  },
  actionText: {
    color: colors.primaryDark,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  actionTextActive: {
    color: colors.white,
  },
  descriptionBox: {
    marginTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.primarySubtle,
    paddingTop: spacing.lg,
  },
  description: {
    color: colors.text,
    fontSize: fontSize.md,
    lineHeight: 22,
  },
  expandButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginTop: spacing.sm,
  },
  expandText: {
    color: colors.primaryDark,
    fontSize: fontSize.sm,
    fontWeight: '900',
  },
  modeBadge: {
    alignSelf: 'flex-start',
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    marginBottom: spacing.sm,
    borderWidth: 1,
  },
  modeBadgeNative: {
    backgroundColor: '#dcfce7',
    borderColor: '#22c55e',
  },
  modeBadgeFallback: {
    backgroundColor: '#ffe4e6',
    borderColor: '#f43f5e',
  },
  modeBadgeText: {
    fontSize: fontSize.xs,
    fontWeight: '900',
  },
  modeBadgeTextNative: {
    color: '#166534',
  },
  modeBadgeTextFallback: {
    color: '#9f1239',
  },
  relatedCard: {
    borderRadius: radius.lg,
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.card,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: fontSize.lg,
    fontWeight: '900',
  },
  sectionHint: {
    color: colors.textSoft,
    fontSize: fontSize.xs,
    fontWeight: '700',
  },
  relatedItem: {
    minHeight: 86,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.primarySubtle,
  },
  relatedCover: {
    width: 104,
    height: 64,
    borderRadius: radius.sm,
    backgroundColor: '#1a1116',
  },
  relatedContent: {
    flex: 1,
    gap: 5,
  },
  relatedTitle: {
    color: colors.text,
    fontSize: fontSize.md,
    fontWeight: '900',
    lineHeight: 19,
  },
  relatedMeta: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    fontWeight: '700',
  },
  relatedStats: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  relatedStatText: {
    color: colors.textSoft,
    fontSize: fontSize.xs,
    fontWeight: '800',
  },
  noRelatedText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    paddingVertical: spacing.md,
  },
  pressed: {
    opacity: 0.74,
  },
  loadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 28,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '900',
    marginTop: spacing.md,
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    lineHeight: 22,
    marginTop: spacing.sm,
    textAlign: 'center',
  },
  errorBanner: {
    position: 'absolute',
    right: spacing.lg,
    bottom: spacing.lg,
    left: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radius.sm,
    padding: spacing.md,
    backgroundColor: colors.danger,
  },
  errorText: {
    flex: 1,
    color: colors.white,
    fontSize: fontSize.sm,
    lineHeight: 18,
  },
});
