import { StyleSheet } from 'react-native';
import { theme } from '@/theme';
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  content: {
    gap: theme.spacing.lg,
    padding: theme.spacing.lg,
    paddingBottom: theme.spacing.xxxl,
  },
  appCard: {
    alignItems: 'center',
    backgroundColor: theme.colors.card,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.sm,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
    ...theme.shadow.card,
  },
  logo: {
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.pill,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  appMeta: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  appName: {
    color: theme.colors.text,
    fontSize: theme.fontSize.xl,
    fontWeight: '900',
  },
  versionText: {
    color: theme.colors.textMuted,
    fontSize: theme.fontSize.sm,
    fontWeight: '700',
  },
  section: {
    backgroundColor: theme.colors.card,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.sm,
    borderWidth: 1,
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
    ...theme.shadow.card,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: theme.colors.text,
    fontSize: theme.fontSize.lg,
    fontWeight: '900',
  },
  row: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.md,
    justifyContent: 'space-between',
    minHeight: theme.touch.minHeight,
  },
  rowText: {
    flex: 1,
    gap: theme.spacing.xs,
  },
  rowTitle: {
    color: theme.colors.text,
    fontSize: theme.fontSize.md,
    fontWeight: '800',
  },
  rowMeta: {
    color: theme.colors.textMuted,
    fontSize: theme.fontSize.sm,
    fontWeight: '700',
    lineHeight: 18,
  },
  optionBlock: {
    gap: theme.spacing.sm,
  },
  optionLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.fontSize.sm,
    fontWeight: '900',
  },
  segmentedControl: {
    backgroundColor: theme.colors.primarySubtle,
    borderRadius: theme.radius.sm,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.xs,
    padding: theme.spacing.xs,
  },
  segmentedItem: {
    alignItems: 'center',
    borderRadius: theme.radius.xs,
    flexGrow: 1,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: theme.spacing.sm,
  },
  segmentedItemSelected: {
    backgroundColor: theme.colors.card,
  },
  segmentedText: {
    color: theme.colors.textMuted,
    fontSize: theme.fontSize.sm,
    fontWeight: '800',
  },
  segmentedTextSelected: {
    color: theme.colors.primaryDark,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  statItem: {
    backgroundColor: theme.colors.cardMuted,
    borderRadius: theme.radius.sm,
    flexBasis: '48%',
    flexGrow: 1,
    gap: theme.spacing.xs,
    minHeight: 64,
    justifyContent: 'center',
    padding: theme.spacing.md,
  },
  statValue: {
    color: theme.colors.primaryDark,
    fontSize: theme.fontSize.lg,
    fontWeight: '900',
  },
  statLabel: {
    color: theme.colors.textMuted,
    fontSize: theme.fontSize.xs,
    fontWeight: '800',
  },
  backendInfo: {
    backgroundColor: theme.colors.primarySubtle,
    borderRadius: theme.radius.sm,
    gap: theme.spacing.xs,
    padding: theme.spacing.md,
  },
  actionRow: {
    alignItems: 'center',
    borderTopColor: theme.colors.primarySubtle,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.md,
    justifyContent: 'space-between',
    minHeight: 56,
    paddingTop: theme.spacing.md,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primarySubtle,
    borderRadius: theme.radius.pill,
    height: theme.touch.iconSmall,
    justifyContent: 'center',
    width: theme.touch.iconSmall,
  },
  pressed: {
    opacity: theme.opacity.pressed,
  },
});
